### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by wpj**
I added a bower.json so that this package can be added to the Bower registry.

### CODE REVIEW

**Comment by vitorleal** [comment]
Great!
It will fix the issue https://github.com/Leaflet/Leaflet.heat/issues/16

**Comment by Volox** [comment]
+1

**Comment by NejcZupec** [comment]
:+1:

**Comment by billxinli** [comment]
+1

**Comment by sebastibe** [comment]
:+1:

**Comment by aboutaaron** [comment]
Please merge!

**Comment by tmcw** [comment]
Can you do

```
bower install git@github.com:Leaflet/Leaflet.heat.git#gh-pages
```

Instead? bower.json & component.json tend to fall out-of-date because maintainers don't use bower, and bower supports install from non-bower-specific git repos. Leaflet.heat is already compatible with browserify and webpack, which is what the authors use.

**Comment by sebastibe** [comment]
> because maintainers don't use bower [but use X and Y instead] 

Isn't it why contributors make PR so maintainers don't have to worry about it?

**Comment by tmcw** [comment]
For the initial release, yes - but after that it becomes another task on the release chores, and and oft-forgotten one - bump package.json, build dists, push to cdns, push git tag, and then update bower.json.

Anyway this is really @mourner's call, being the principal author of this module.

**Comment by mourner** [comment]
See https://github.com/Leaflet/Leaflet.heat/issues/16#issuecomment-155834094

**Pull request closed without merging**
