### PR TITLE
A more useful relative heat map

### PR DESCRIPTION
**Pull request by Guitlle**
I believe it is more important to have a relative heatmap. This means that the maximum value in the visible points should be the hottest and the minimum should be the coolests. This is done by getting the maximum and the minimum and making it get a range and an offset.

### CODE REVIEW

**Comment by mweinelt** [comment]
Please implement this, it would make the heat maps so much more useful.

**Comment by marks** [comment]
+1

**Comment by doomsuckle** [comment]
Didn't I meet you at health datapalooza?

-----Original Message-----

**Comment by marks** [comment]
Yup!

Mark Silverberg http://SocialHealthInsights.comhttp://SocialHealthInsights.com
Sent from my iPhone

On Jun 11, 2014, at 12:08 AM, "doomsuckle" <notifications@github.com<mailto:notifications@github.com>> wrote:

Didn't I meet you at health datapalooza?

-----Original Message-----

**Comment by grotheandreas1** [comment]
Many thanks for your contribution, this is exactly what I was looking for!

There is an issue in '_redraw()' when calculating the min/max values, though:
An alt sequence of eg. [0, 10] would give a min value of '10' because 'if (min == false)' is 'true' in the second iteration ('0 == false' is 'true' in javascript). Perhaps an alternative approach would be to use 'var min=0, max=0; ... min=Math.min(min,value); max=Math.max(max,value))' instead?

**Comment by Guitlle** [comment]
Thanks grotheandreas1, I'll fix it

**Comment by danzel** [comment]
Use a `===` instead

**Comment by jbouzekri** [comment]
Hi everyone, it would be very useful to have a relative heat map. 
@DuGuille will you be able to finish this ?

**Comment by Guitlle** [comment]
Hi jbouzekri. it's been a while since I posted this. I'll try to finish it this weekend.

**Comment by jbouzekri** [comment]
Many thanks !!!!

**Comment by spaasis** [comment]
@DuGuille Any update on the schedule? This would be an extremely nice feature

**Comment by Guitlle** [comment]
Hi. I've found a much better way of doing this. Made a new branch and a new pull request  #58

**Pull request closed without merging**
